# Generated by Django 5.1.3 on 2024-11-16 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['name', 'date'], name='dashboard_d_name_96c703_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['-date'], name='dashboard_d_date_054a27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together={('name', 'date')},
        ),
        migrations.AddField(
            model_name='dashboardstat',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.organization'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_7f2c17_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='dashboard_a_activit_837855_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstat',
            index=models.Index(fields=['created_at'], name='dashboard_d_created_f49852_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstat',
            index=models.Index(fields=['organization', 'created_at'], name='dashboard_d_organiz_5aaac2_idx'),
        ),
    ]
