# Generated by Django 5.1.3 on 2024-11-17 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['student', 'status'], name='reports_rep_student_007e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['mentor', 'status'], name='reports_rep_mentor__b705fe_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['internship', '-created_at'], name='reports_rep_interns_d821bf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['type', 'status'], name='reports_rep_type_9ff8af_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-submission_date'], name='reports_rep_submiss_831bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['report', 'created_at'], name='reports_rep_report__32ad4d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['author', 'created_at'], name='reports_rep_author__6c00c5_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__11a031_idx'),
        ),
    ]
